### ISSUE TITLE
Question about data vis libs

### ISSUE THREAD

**Issue by ninja542** [ByrdOfAFeather/AlphaTrion#3]
Why do you have two different data visualization libraries?

**Comment by ByrdOfAFeather** [comment]
Bokeh handles the Python side of the code and serves as an API wrapper for the vis.js library side of the code. This way I query the data directly into the javascript from Python. The best (and only) example of this is in the overall community analysis view:
 
https://github.com/ByrdOfAFeather/AlphaTrion/blob/master/Community/views/data_analysis.py
